Repository be15-fin-project/be15-fin-DAO-Momentum-BE, pull requests merged in 2025-07, with the labels that each got.

#285 [feat] 근무 유형, 휴가 유형 조회 기능 작성
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: feat

#288 feat: 결제 알림 기능 구현
  momentum-dao-be/.gitignore
  momentum-dao-be/Dockerfile
  momentum-dao-be/docker-compose.yml
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/FormDetailStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/BusinessTripFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/CancelFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/OvertimeFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ProposalFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ReceiptFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/RemoteWorkFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/VacationFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/WorkCorrectionFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveCancelRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveProposalRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveReceiptRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/KafkaConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/kafka/dto/NotificationMessage.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/Notification.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/NotificationTemplate.java
  momentum-dao-be/src/main/resources/application.yml
Labels: init, feat

#291 refactor : 상위 부서 필터링 수정 및 평가 제출 목록 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluatorRoleDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/EvaluationTaskMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationTaskServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/ExcelEvaluationQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiStatisticsMapper.xml
Labels: refactor

#293 refactor : 평가 등록일 기준 수정 및 테스트 코드 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalRoundServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationManageController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationRoundSimpleDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTaskResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/EvaluationManageMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/controller/KpiApprovalController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/controller/KpiCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiEmployeeSummaryRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiStatisticsServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationManageMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalRoundServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationTaskControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvaluationTaskServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/controller/KpiStatisticsControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/service/KpiStatisticsServiceImplTest.java
Labels: refactor

#295 refactor: 사원 등록 request 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRegisterRequest.java
Labels: feat

#294 refactor: 회사 정보 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/CompanyInfoDTO.java
  momentum-dao-be/src/main/resources/mappers/organization/CompanyMapper.xml
Labels: feat

#300 fix: S3 Presigned URL 업로드 시, ContentType 및 ContentDisposition 헤더 설정
  momentum-dao-be/src/main/java/com/dao/momentum/common/s3/S3Service.java
Labels: fix

#298 fix: 사원 목록 조회 쿼리 수정
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
Labels: fix

#303 feat 평가 종류 트리 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationManageController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/EvaluationFormPropertyRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationFormDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationFormPropertyDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTypeDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTypeTreeResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/EvaluationManageMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationManageMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationManageControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvaluationManageServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
Labels: feat

#307 refactor: 발령 내역 조회 쿼리 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/AppointCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchRequest.java
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
Labels: refactor

#309 [test] 회사 정보 조회 테스트 수정
  momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
Labels: fix

#313 refactor: 파일 엔티티에 name 컬럼 추가 -> 공지사항 업로드, 수정, 조회 로직 리팩토링, S3 PresignedURL 생성 시 Content-Disposition 헤더 설정 해제
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/query/dto/response/AnnouncementDetailDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/s3/S3Service.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/controller/FileController.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/request/AttachmentRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/request/DownloadUrlRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/AttachmentDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/DownloadUrlResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/service/FileService.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/aggregate/File.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/controller/AnnouncementCommandControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandServiceTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/controller/AnnouncementQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/service/AnnouncementQueryServiceTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/file/command/application/controller/FileControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/file/command/application/service/FileServiceTest.java
Labels: refactor, test

#315 refactor: 출퇴근 등록 쿼리 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/mapper/HolidayMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/service/HolidayQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/AttendanceDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/AttendanceResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/IsAttended.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/VacationTypeEnum.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkTypeName.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/HolidayMapper.xml
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#316 fix: 본인 출퇴근 내역 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkListResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/work/query/service/WorkQueryServiceTest.java
Labels: fix

#317 test : 테스트 코드 수정
  momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
Labels: fix, test

#319 feat: 인사 평가 이의제기 요청 상세 조회 추가
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/controller/HrObjectionQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyHrEvaluationListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyObjectionListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/request/MyObjectionRaw.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/MyObjectionItemDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/mapper/HrObjectionMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationHrMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/HrObjectionMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/MyObjectionMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/controller/HrObjectionQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java
Labels: feat

#327 refactor: 본인 출퇴근 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/MyWorkDTO.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#328 refactor : 인사 평가 이의제기 권한 확인 로직 추가 및 여러 에러 처리
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalRoundServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalResponseRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalRoundRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/EvaluationTaskResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/controller/HrObjectionProcessController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/facade/HrObjectionProcessFacade.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionInsightDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/service/RetentionInsightCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/aggregate/RetentionInsight.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionSupportExcelDownloadController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionStatisticsRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportExcelDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/StabilityRatioByDeptRaw.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionAverageScoreDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/StabilityDistributionByDeptDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/mapper/RetentionSupportExcelMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/util/ExcelGenerator.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationHrMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/ExcelEvaluationQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportExcelMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalRoundServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/controller/HrObjectionQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/HrObjectionQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/command/application/service/RetentionInsightCommandServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImplTest.java
Labels: refactor

#332 refactor: 공지사항 목록 조회 -> 하위 부서까지 한번에 목록 조회
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
Labels: refactor

#334 refactor : 근속 전망 상세 조회 정보 수정
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionForecastCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/response/RetentionForecastCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/facade/RetentionForecastFacade.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/repository/RetentionRoundRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportRaw.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionForecastItemDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionSupportDetailDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
Labels: refactor

#336 fix : 첨부 파일 관련된 부분에 name 속성 추가
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java
  momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/DraftApproveMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
Labels: fix, refactor

#338 refactor: 이메일 처리 메소드 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
  momentum-dao-be/src/main/java/com/dao/momentum/email/service/EmailService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/resources/templates/email/init-password.html
Labels: refactor

#341 refactor: 사원 목록 조회, 출퇴근 목록 조회 시 부서 필터링 수정
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#342 refactor: 공지사항 상세 조회 -> 첨부파일 리스트 Dto 안에 fileId 추가
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/dto/response/AttachmentDto.java
  momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
Labels: refactor

#345 refactor : 평가 제출 목록 정렬 조건 수정
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationTaskMapper.xml
Labels: refactor

#350 fix: 계약서 등록 시 파일명 추가
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
Labels: fix

#344 refactor: position 엔드포인트 권한 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
Labels: refactor

#352 feat : 프론트와의 기능 연동을 위한 필드 추가
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineListDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/EmployeeLeaderDto.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml
Labels: feat

#349 test : KPI 철회 테스트 코드 구현
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/domain/aggregate/Kpi.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiCommandServiceImplTest.java
Labels: test

#355 feat : 대시보드 KPI 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiDashboardRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/response/KpiDashboardResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/mapper/KpiQueryMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImplTest.java
Labels: feat

#357 refactor : 영수증 내역에서 필드명 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ReceiptFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
Labels: refactor

#360 refactor: 근태 전체 내역 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#362 초과 근무에서 초과 근무 유형이 안보이는 문제 해결
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
Labels: fix

#364 fix: 직위 생성 및 수정 로직 변경
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
Labels: fix

#372 [fix] run 실패 문제 해결
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/aggregate/RetentionSupport.java
Labels: fix

#371 refactor : endpoint 변경 및 조회 관련 오류 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/RemainingVacationQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
Labels: fix, refactor

#373 feat: 근속 지원 점수 계산 메서드 반영
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractRetentionService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkRetentionService.java
Labels: feat

#377 fix : 받은 문서 조회 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java
  momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
Labels: fix

#376 refactor : 근속 전망 통계 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DeptHeadRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepHeadRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/ManagerFinderService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/facade/RetentionForecastFacade.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/service/RetentionSupportCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/domain/aggregate/StabilityType.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/StabilityRatioByDeptRaw.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionAverageScoreDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionMonthlyStatDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionProgressDistributionDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/StabilityRatioByDeptDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/StabilityRatioSummaryDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/mapper/RetentionStatisticsMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionRoundMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/controller/RetentionStatisticsQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/controller/RetentionSupportQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImplTest.java
Labels: refactor

#378 fix: 사원 목록 조회 쿼리 수정
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
Labels: fix

#379 refactor: 근태 내역 조회 쿼리 수정
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#380 refactor : KPI 감점 계산, 통계 유형 조회, 평가 기본 점수 수정
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationScoreServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/util/KpiPenaltyCalculator.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml
Labels: refactor

#381 fix : 조회 가능 한 결재만 조회 할 수 있게 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveDetailMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
Labels: fix, refactor

#383 feat : 결재 문서 회수 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveCancelRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineListRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveProposalRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveReceiptRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRefRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/repository/FileRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/BusinessTripRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/OvertimeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/RemoteWorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkCorrectionRepository.java
Labels: feat

#385 [refactor #37] 사원 CSV 일괄 등록 로직 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRegisterRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/VacationTimesDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/VacationTimesResponse.java
Labels: refactor

#388 refactor : 결재 상세 조회 시 참조자의 empId도 조회할 수 있게 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveRefDTO.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
Labels: refactor

#386 refactor : KPI, HR 조회 문제 수정
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/HrEvaluationListResultDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/dto/response/HrEvaluationWithFactorsDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/EvaluationHrServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiRequestQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/evaluation/EvaluationHrMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/MyObjectionMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/controller/EvaluationHrControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/EvaluationHrServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/command/application/service/RetentionInsightCommandServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportQueryServiceImplTest.java
Labels: refactor

#387 fix: 사원 발령 등록 및 조회 기능 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/AppointCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/AppointDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/AppointCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Appoint.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/AppointRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/AppointDTO.java
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
Labels: fix, refactor

#393 init : SecurityConfig 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
Labels: init

#395 test: 부서 관련 테스트코드 작성
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/request/DepartmentUpdateRequest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/department/command/application/service/DepartmentCommandServiceTest.java
Labels: test

#397 test : 테스트 코드 수정
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadServiceImplTest.java
Labels: test

#396 test: 직위 테스트코드 수정
  momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
Labels: test

#398 test: 휴일 관련 테스트코드 작성
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Holiday.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetDTO.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/company/command/application/service/HolidayCommandServiceTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/HolidayQueryServiceTest.java
Labels: test

#399 refactor : 인사 평가 이의제기 요청 내역 조회 문제 수정
  momentum-dao-be/src/main/resources/mappers/evaluation/HrObjectionMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportExcelMapper.xml
Labels: refactor

#402 refactor : 근속 전망 로그 추가 및 로직 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractRetentionService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/calculator/RetentionScoreCalculatorImpl.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/interview/command/application/service/RetentionContactCommandServiceImplTest.java
Labels: refactor, feat

#406 teat : 테스트 에러 해결
  momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
Labels: test

#408 fix : 결재 문서 회수 관련 문제 해결
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/repository/NotificationRepository.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImplTest.java
Labels: fix

#410 refactor: 백엔드 서버 WARN 로그 해결
  momentum-dao-be/src/main/resources/application.yml
Labels: refactor

#405 feat: 비밀번호 재설정 관련 api 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
Labels: fix, feat

#411 refactor: CSV 에러 메시지 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
Labels: refactor

#415 refactor: 계약서 삭제, CSV 등록 로직 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
Labels: refactor
