Repository be15-fin-project/be15-fin-DAO-Momentum-BE, pull requests merged in 2025-06, with the labels that each got.

#5 [feat #4] ApiResponse 및 Pagination 생성
  momentum-dao-be/src/main/java/com/dao/momentum/common/dto/ApiResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/dto/Pagination.java
Labels: feat

#16 [feat] ErrorCode 및 GlobalExceptionHandler 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
Labels: feat

#15 [init] 근태 관리 기능 구현을 위한 초기 세팅
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/IsNormalWork.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkType.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkTypeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/infrastructure/repository/JpaWorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/infrastructure/repository/JpaWorkTypeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/dummy.txt
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
  momentum-dao-be/src/main/resources/mappers/work/mapper.txt
Labels: init

#17 [init] 사원 기능 구현을 위한 초기 세팅
  momentum-dao-be/build.gradle
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/ModelMapperConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/dump.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/jwt/RestAccessDeniedHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRoles.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Gender.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Status.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/UserRole.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/UserRoleName.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaEmployeeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/EmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/dummy.txt
Labels: init

#20 init: 알림, 알림 템플릿 엔티티 생성
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/IsRead.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/Notification.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/NotificationTemplate.java
  momentum-dao-be/src/main/java/com/dao/momentum/notification/command/domain/aggregate/dummy.txt
Labels: init

#61 init : 결재 엔티티 생성
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveProposal.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveRef.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveType.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/IsConfirmed.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/IsRequiredAll.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ReceiptType.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/temp/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/temp/command/application/dto/response/dummy.txt
Labels: init

#119 [init] Contract 엔티티 생성
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/Contract.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/ContractType.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/dummy.txt
Labels: init

#121 Department 엔티티 생성
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/Department.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/DeptHead.java
Labels: init

#100 feat: 출근 등록 기능 구현
  .idea/backend.iml
  .idea/vcs.xml
  momentum-dao-be/build.gradle
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/request/WorkStartRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkStartResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkSummaryDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkTimeService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/validator/IpValidator.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/validator/WorkCreateValidator.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkType.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkTypeName.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkTypeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/exception/WorkException.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/exception/dummy.txt
  momentum-dao-be/src/test/java/com/dao/momentum/work/command/application/controller/WorkCommandControllerTest.java
Labels: feat

#122 Compay, IpAddress, Holiday 엔티티 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Company.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Holiday.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/IpAddress.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/dummy.txt
Labels: init

#126 feat : 전체 결재 문서 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/infrastructure/api/NaverOcrApi.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/NotExistTabException.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/ApproveListRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/PageRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/ApproveResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/AdminApproveMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml
  momentum-dao-be/src/main/resources/mappers/approve/mapper.txt
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveServiceImplTest.java
Labels: feat

#128 feat: 직위 등록 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/request/PositionCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/response/PositionCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/aggregate/Position.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/exception/PositionException.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/exception/dummy.txt
  momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
Labels: feat

#132 feat : 받은 문서 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveServiceImplTest.java
Labels: feat

#134 feat: 직위 수정 기능 구현
  .idea/misc.xml
  .idea/workspace.xml
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/request/PositionUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/dto/response/PositionUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/service/PositionCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/aggregate/Position.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/exception/PositionException.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/position/command/application/service/PositionCommandServiceTest.java
Labels: feat

#133 [test #3, #6] 결재 내역 조회 컨트롤러, 서비스 테스트 코드 수정
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveServiceImplTest.java
Labels: test

#141 refactor : 클래스명 변경 (Query 추가)
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ReceivedApproveMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/approve/ReceivedApproveMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
Labels: refactor

#143 refactor: company entity 수정, 출퇴근 조회 쿼리 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/dto/request/CompanyUpdateDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/dto/request/CompanyUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/aggregate/Company.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#145 test: CompanyQueryServiceTest 테스트 코드 수정
  .gitignore
  .idea/.gitignore
  .idea/modules.xml
  .idea/workspace.xml
  momentum-dao-be/src/test/java/com/dao/momentum/MomentumDaoBeApplicationTests.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/company/query/service/CompanyQueryServiceTest.java
Labels: test

#148 feat: 로그아웃 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
Labels: feat

#152 init ERD 수정에 따른 entity 수정
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/command/domain/aggregate/EvalPrompt.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/command/domain/aggregate/HrWeight.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionInsight.java
Labels: init

#147 feat : 결재 문서 상세 조회 기능
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveType.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/NotFoundApproveException.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineGroupDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveLineListDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveRefDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveCancelDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveProposalDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/BusinessTripDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/OvertimeDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/RemoteWorkDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/VacationDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/WorkCorrectionDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/request/ApproveListRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/response/ApproveDetailResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveDetailMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/AdminApproveQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
Labels: feat

#153 feat: KPI 종합 현황 통계 조회 기능
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/exception/KpiException.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/controller/KpiStatisticsController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/dto/request/KpiStatisticsRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/dto/response/KpiStatisticsResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/mapper/KpiStatisticsMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/service/KpiStatisticsService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/service/KpiStatisticsServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/query/service/dummy.txt
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiStatisticsMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/mapper.txt
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/query/controller/KpiStatisticsControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/query/service/KpiStatisticsServiceImplTest.java
Labels: feat

#150 test: 로그인 및 로그아웃 테스트코드 작성
  momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/controller/AuthControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/service/AuthServiceTest.java
Labels: test

#154 init : 취소 결재 엔티티 추가
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveCancel.java
Labels: init

#146 feat: 공지사항 상세 조회, S3 Presigned URL 기반 업로드 구현
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/controller/AnnouncementCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/dto/request/AnnouncementCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/dto/request/AnnouncementModifyRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/dto/request/AttachmentRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/dto/request/FilePresignedUrlRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/dto/response/FilePresignedUrlResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/S3Config.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/service/S3Service.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/controller/AnnouncementCommandControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandServiceTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/controller/AnnouncementQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/query/service/AnnouncementQueryServiceTest.java
Labels: feat, test

#156 feat: 토큰 갱신 기능 구현 및 테스트코드 작성
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
  momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/controller/AuthControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/common/auth/application/service/AuthServiceTest.java
Labels: test

#167 feat: 사원 기본 정보 수정 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeInfoUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeInfoDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeInfoUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
Labels: feat

#168 refactor: http 응답 코드 수정
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java
  momentum-dao-be/src/test/java/com/dao/momentum/work/command/application/controller/WorkCommandControllerTest.java
Labels: refactor

#169 feat: 사원 인사 정보 수정 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRecordsUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeRecordsUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRecords.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRecordsRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java
Labels: feat

#172 feat: 사원 간 평가 및 조직 평가 내역 조회 및 세부 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/OrgEvaluationListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/PeerEvaluationListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/FactorScoreDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/OrgEvaluationListResultDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/OrgEvaluationResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationDetailResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationDetailResultDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationListResultDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/OrgEvaluationMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/PeerEvaluationMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvaluationQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/dummy.txt
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiRequestMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/OrgEvaluationMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/PeerEvaluationMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/controller/EvaluationQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvaluationQueryServiceImplTest.java
Labels: feat

#173 refactor: workmapper 불필요한 import 문 삭제
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
Labels: refactor

#171 feat: 사원 발령 등록 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/JpaDepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/exception/DepartmentException.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/AppointCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/AppointCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/AppointDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Appoint.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/AppointType.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/AppointRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaAppointRepository.java
Labels: feat

#181 feat: 알림 발송 템플릿 구현
  momentum-dao-be/build.gradle
  momentum-dao-be/docker-compose.yml
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/KafkaConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/kafka/dto/NotificationMessage.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/kafka/producer/NotificationKafkaProducer.java
  momentum-dao-be/src/main/resources/application.yml
Labels: feat

#161 feat: 사원 등록 시 메일 전송 기능 구현
  momentum-dao-be/build.gradle
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/jwt/JwtTokenProvider.java
  momentum-dao-be/src/main/java/com/dao/momentum/email/exception/EmailFailException.java
  momentum-dao-be/src/main/java/com/dao/momentum/email/service/EmailService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/resources/application.yml
  momentum-dao-be/src/main/resources/templates/email/reset-password.html
  momentum-dao-be/src/test/java/com/dao/momentum/email/service/EmailServiceTest.java
Labels: feat, test

#186 refactor : 엔티티에서 default 값 설정 및 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveReceipt.java
Labels: refactor

#187 feat: 사원 비밀번호 변경 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/request/PasswordResetRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/domain/aggregate/PasswordResetToken.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/RedisConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/jwt/JwtTokenProvider.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/resources/templates/email/reset-password.html
Labels: feat

#188 feat: 계약서 등록, 삭제 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/repository/FileRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/controller/ContractCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/request/ContractCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/response/ContractCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/response/ContractDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/response/ContractDeleteResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/aggregate/Contract.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/repository/ContractRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/infrastructure/repository/JpaContractRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/exception/ContractException.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
Labels: feat

#192 feat: File 엔티티 url 필드 -> s3Key로 수정
  momentum-dao-be/src/main/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/domain/aggregate/File.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/service/ContractCommandService.java
  momentum-dao-be/src/main/resources/mappers/announcement/query/mapper/AnnouncementQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/organization/ContractMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/announcement/command/application/service/AnnouncementCommandServiceTest.java
Labels: feat

#195 [feat #94 #95] 면담 기록 내역 조회 및 면담 요청 내역 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/controller/RetentionContactQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionContactListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionForecastRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionSupportRaw.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactDetailDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactItemDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionContactListResultDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionForecastItemDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionContactMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionStatisticsMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionContactQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionContactQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionSupportQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionContactMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/controller/RetentionContactQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/service/RetentionContactQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImplTest.java
Labels: feat

#193 feat: 사원 발령 내역 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointSearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/AppointType.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/AppointDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/AppointListResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/AdminEmployeeMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/AdminEmployeeQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/AdminEmployeeMapper.xml
Labels: feat

#201 feat: 비밀번호 재설정 요청 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/request/PasswordResetLinkRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/response/PasswordResetResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
Labels: feat

#202 feat : 근속 전망 상세 조회 기능 구현 및 전체 및 부서별 근속 안정성 비율 조회 db 활용하도록 리펙토링
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionSupport.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/controller/RetentionStatisticsQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/controller/RetentionSupportQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionInsightRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/request/RetentionSupportDetailRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionGroupStatisticsDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionStatisticsResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/RetentionSupportDetailDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/dto/response/StabilityDistributionByDeptDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionStatisticsMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/mapper/RetentionSupportMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionSupportQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/query/service/RetentionSupportQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionStatisticsMapper.xml
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/controller/RetentionStatisticsQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/controller/RetentionSupportQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/query/service/RetentionStatisticsQueryServiceImplTest.java
Labels: feat

#205 feat: 비밀번호 변경 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/controller/AuthController.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/request/PasswordChangeRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/dto/response/PasswordChangeResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/auth/application/service/AuthService.java
Labels: feat

#194 feat : 영수증 결재 내역 추출 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/ReceiptOcrResultResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/OcrService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/OcrServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/infrastructure/api/NaverOcrApi.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/OcrRequestFailedException.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/resources/application.yml
Labels: feat

#204 feat: 사원 CSV 등록 기능 구현
  momentum-dao-be/build.gradle
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/service/FileService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/EmployeeCSVResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/exception/EmployeeException.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/domain/repository/PositionRepository.java
Labels: feat

#208 feat: KPI 제출 및 제출 승인/반려 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/controller/KpiApprovalController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/controller/KpiCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/dto/request/KpiApprovalRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/dto/request/KpiCancelApprovalRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/dto/request/KpiProgressUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/dto/response/KpiApprovalResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/dto/response/KpiProgressUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiApprovalService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiApprovalServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/command/domain/aggregate/Kpi.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiApprovalServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/command/application/service/KpiCommandServiceImplTest.java
Labels: feat

#207 refactor : 영수증 결재 내역에 주소 컬럼 추가 및 mapper 쿼리 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/ApproveReceiptDTO.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
Labels: refactor

#214 feat : 결재 문서 작성 구현
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineListRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRefRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveCancelRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveProposalRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveReceiptRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/BusinessTripRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/OvertimeRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/RemoteWorkRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/VacationRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/WorkCorrectionRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/FormDetailStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/FormDetailStrategyDispatcher.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/BusinessTripFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/CancelFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/OvertimeFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ProposalFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/ReceiptFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/RemoteWorkFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/VacationFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/strategy/form/WorkCorrectionFormStrategy.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveCancelRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineListRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveProposalRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveReceiptRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRefRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/ApproveException.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/exception/ReceiptApproveException.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/GlobalExceptionHandler.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/BusinessTrip.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Overtime.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/RemoteWork.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Vacation.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkCorrection.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/BusinessTripRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/OvertimeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/RemoteWorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkCorrectionRepository.java
Labels: feat

#212 feat: CSV 양식 다운로드 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/file/command/application/service/FileService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
Labels: feat

#216 refactor: empNo 자료형 변경
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/request/AdminContractSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/request/AdminContractSearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/query/dto/response/AdminContractDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/Department.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/controller/DepartmentQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/mapper/DepartmentMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/AdminWorkSearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/WorkSearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/WorkSearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: refactor

#217 feat : 결재 상세 내역 조회 기능 추가 및 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/ApproveFileDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/approveTypeDTO/OvertimeDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveDetailMapper.xml
Labels: feat

#221 feat : 면담 요청 기눙 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/RetentionContactCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/CreateRetentionContactRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactCreateDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/RetentionContactResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/aggregate/RetentionContact.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepositoryImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/infrastructure/repository/JpaRetentionContactRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/infrastructure/repository/dummy.txt
Labels: feat

#219 feat: 부서 상세 조회 기능, 부서 등록 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/controller/DepartmentCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/request/DepartmentCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/response/DepartmentCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/service/DepartmentCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/aggregate/Department.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/command/domain/repository/DepartmentRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/controller/DepartmentQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/dto/response/DepartmentDetailDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/dto/response/DepartmentDetailResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/mapper/DepartmentMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/department/query/service/DepartmentQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/DepartmentMemberDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/EmployeeMapper.java
  momentum-dao-be/src/main/resources/mappers/organization/DepartmentMapper.xml
  momentum-dao-be/src/main/resources/mappers/organization/EmployeeMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/organization/department/command/application/controller/DepartmentCommandControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/department/command/application/service/DepartmentCommandServiceTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/department/query/controller/DepartmentQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/organization/department/query/service/DepartmentQueryServiceTest.java
Labels: feat, test

#223 feat: 지급 휴가일 계산 로직 구현
  momentum-dao-be/src/main/java/com/dao/momentum/MomentumDaoBeApplication.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/AppointCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/VacationTimeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/VacationComputeDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/VacationComputeRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/VacationTimesDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/VacationTimesResponse.java
  momentum-dao-be/src/test/java/com/dao/momentum/work/command/application/service/WorkCommandServiceTest.java
Labels: feat

#224 feat: 면담 요청 삭제 및 면담 보고 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/dto/UseStatus.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/controller/RetentionContactCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactDeleteDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactFeedbackUpdateDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactFeedbackUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactResponseUpdateDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/request/RetentionContactResponseUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/RetentionContactDeleteResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/RetentionContactFeedbackUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/dto/response/RetentionContactResponseUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/command/domain/repository/RetentionContactRepositoryImpl.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/command/application/service/RetentionContactCommandServiceImplTest.java
Labels: feat

#227 feat : 인사 평가 이의 제기 승인/반려 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/dto/request/EvalFactorScoreDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculator.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculatorImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/aggregate/EvalResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/aggregate/EvalScore.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalResponseRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalScoreRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/domain/repository/EvalScoreRepositoryImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/infrastructure/repository/JpaEvalResponseRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/command/infrastructure/repository/JpaEvalScoreRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/controller/HrObjectionProcessController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/dto/request/HrObjectionProcessRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/dto/response/HrObjectionProcessResponseDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/facade/HrObjectionProcessFacade.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/domain/aggregate/HrObjection.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/domain/repository/HrObjectionRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/hr/command/infrastructure/repository/HrObjectionJpaRepository.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalResponseServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreCalculatorImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/command/application/service/EvalScoreServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/command/application/service/HrObjectionServiceImplTest.java
Labels: feat

#230 refactor: 불필요한 import 문 제거
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Appoint.java
Labels: refactor

#226 feat: 사원 발령 등록 배치 작업 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/AppointCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/VacationTimeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/AppointRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/request/VacationComputeDTO.java
Labels: feat

#232 refactor: 출퇴근 spring security 설정 추가, swagger 어노테이션 수정
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/controller/WorkCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java
Labels: refactor

#235 refactor: 사원 관리 security config 추가
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/VacationTimeCommandService.java
Labels: refactor

#239 feat: 사원 개인 정보 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/EmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/AdminEmployeeQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java
Labels: feat

#240 feat : 근속 전망 엑셀 다운로드 기능 구현
  momentum-dao-be/build.gradle
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/controller/RetentionForecastController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionForecastCreateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionInsightDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/request/RetentionSupportDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/command/application/dto/response/RetentionForecastCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/controller/RetentionSupportExcelDownloadController.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportExcelDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/response/RetentionAverageScoreDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/mapper/RetentionSupportExcelMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadService.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/util/ExcelGenerator.java
  momentum-dao-be/src/main/resources/mappers/retention/RetentionSupportExcelMapper.xml
Labels: feat

#245 test: 근속 전망 엑셀 다운로드 기능 테스트 코드 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/dto/request/RetentionSupportExcelDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionRoundQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImpl.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/command/application/service/RetentionInsightCommandServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionSupportExcelDownloadServiceImplTest.java
Labels: test

#247 feat: 평가별 엑셀 다운로드 기능 - 사원간 평가
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/controller/ExcelEvaluationDownloadController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/request/PeerEvaluationExcelRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/dto/response/PeerEvaluationExcelDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/mapper/ExcelEvaluationQueryMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/EvalFormQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadService.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/eval/query/util/PeerEvaluationExcelGenerator.java
  momentum-dao-be/src/main/resources/mappers/evaluation/ExcelEvaluationQueryMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/ExcelEvaluationDownloadServiceImplTest.java
Labels: feat

#246 feat: 사원 기본 정보 수정 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/MyInfoUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/MyInfoUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/Employee.java
Labels: feat

#251 feat : 결재 승인, 반려 기능 구현하기
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/controller/ApproveCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApprovalConfirmRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalCancelCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApprovalDecisionCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/service/ApproveCommandServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/Approve.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLine.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/aggregate/ApproveLineList.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineListRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveLineRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/domain/repository/ApproveRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/service/WorkApplyCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/BusinessTrip.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Overtime.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/RemoteWork.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Vacation.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/Work.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/aggregate/WorkCorrection.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/BusinessTripRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/OvertimeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/RemoteWorkRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/VacationTypeRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/domain/repository/WorkCorrectionRepository.java
Labels: feat

#249 feat: 권한 목록 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/UserRoleRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaEmployeeRolesRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/infrastructure/repository/JpaUserRoleRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/UserRoleDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/UserRolesResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/UserRoleMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/UserRoleMapper.xml
Labels: feat

#255 feat: 권한 수정 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/controller/EmployeeCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/RoleUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/response/RoleUpdateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRoles.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRolesRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/UserRoleRepository.java
Labels: feat

#253 feat: 회사 휴일 등록 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/exception/ErrorCode.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/controller/HolidayCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/dto/request/HolidayCrateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/dto/response/HolidayCreateResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/application/service/HolidayCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/command/domain/repository/HolidayRepository.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/application/controller/dummy.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/application/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/application/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/application/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/application/service/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/domain/aggregate/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/domain/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/command/infrastructure/repository/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/exception/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/query/controller/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/query/dto/response/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/query/mapper/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/holiday/query/service/dummy.txt
Labels: feat

#258 refactor: ApiResponse로 감싸지 않은 응답 수정
  momentum-dao-be/src/main/java/com/dao/momentum/organization/contract/command/application/controller/ContractCommandController.java
Labels: refactor

#257 feat: 특정 사원 권한 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/controller/AdminEmployeeQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRoleDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRolesResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/mapper/UserRoleMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/service/EmployeeQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/UserRoleMapper.xml
Labels: feat

#261 docs: 사원 권한 swagger 어노테이션 추가
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRoleDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/query/dto/response/EmployeeRolesResponse.java
Labels: refactor

#259 feat: 휴일 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/controller/HolidayQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/request/HolidaySearchDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/request/HolidaySearchRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/request/dummy.txt
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/HolidayGetResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/mapper/HolidayMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/service/HolidayQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/HolidayMapper.xml
Labels: feat

#263 refactor: 근무 swagger 어노테이션 추가
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkEndResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkStartResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/command/application/dto/response/WorkSummaryDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/IsNormalWork.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkListResponse.java
Labels: refactor

#265 refactor : 결재 문서 작성 요청, 응답 객체에 description 추가
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineListRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveLineRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRefRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/ApproveRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveCancelRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveProposalRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/ApproveReceiptRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/BusinessTripRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/OvertimeRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/RemoteWorkRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/VacationRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/request/approveType/WorkCorrectionRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/command/application/dto/response/ReceiptOcrResultResponse.java
Labels: refactor

#267 feat: 캘린더 회사 휴일 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/controller/HolidayQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/dto/response/MonthPerHolidayGetResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/mapper/HolidayMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/company/query/service/HolidayQueryService.java
  momentum-dao-be/src/main/resources/mappers/organization/HolidayMapper.xml
Labels: feat

#268 feat: 출퇴근 상세 내용 조회 기능 구현
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/dto/request/EmployeeRecordsUpdateRequest.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/CSVService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/application/service/EmployeeCommandService.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/EmployeeRecords.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/aggregate/RecordType.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/controller/WorkQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/request/Order.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDetailsDTO.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/dto/response/WorkDetailsResponse.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/mapper/WorkMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/work/query/service/WorkQueryService.java
  momentum-dao-be/src/main/resources/mappers/work/WorkMapper.xml
Labels: feat

#271 test : 예외처리 변경으로 인한 테스트 코드 오류 수정
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/eval/query/service/EvalFormQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/hr/query/service/MyObjectionQueryServiceImplTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/evaluation/kpi/query/controller/KpiStatisticsControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/retention/prospect/query/service/RetentionStatisticsQueryServiceImplTest.java
Labels: test

#276 feat : 사원의 팀장 조회하기
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/ApproveQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/dto/EmployeeLeaderDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/mapper/ApproveMapper.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryService.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImpl.java
  momentum-dao-be/src/main/resources/mappers/approve/ApproveMapper.xml
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/controller/ApproveQueryControllerTest.java
  momentum-dao-be/src/test/java/com/dao/momentum/approve/query/service/ApproveQueryServiceImplTest.java
Labels: feat

#277 [refactor] 불필요 메소드 및 import문 제거
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/application/controller/PositionCommandController.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/position/command/infrastructure/repository/JpaPositionRepository.java
Labels: refactor

#278 refactor : 필터링 변경 및 empId 호출 방식 변경
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiRequestQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/controller/KpiStatisticsController.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiEmployeeSummaryRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiRequestListRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiStatisticsRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/dto/request/KpiTimeseriesRequestDto.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/evaluation/kpi/query/service/KpiStatisticsServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/organization/employee/command/domain/repository/EmployeeRepository.java
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiQueryMapper.xml
  momentum-dao-be/src/main/resources/mappers/evaluation/KpiStatisticsMapper.xml
Labels: refactor

#286 refactor : 결재 조회 권한 설정 수정
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/controller/AdminApproveQueryController.java
  momentum-dao-be/src/main/java/com/dao/momentum/approve/query/service/AdminApproveQueryServiceImpl.java
  momentum-dao-be/src/main/java/com/dao/momentum/common/config/SecurityConfig.java
  momentum-dao-be/src/main/resources/mappers/approve/AdminApproveMapper.xml
Labels: refactor
